name: Lint and Format

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: |
          if ! npm run lint; then
            echo "::error::ESLint found issues. Run 'npm run lint:fix' to automatically fix some issues."
            exit 1
          fi

      - name: Check Prettier formatting
        run: |
          if ! npm run format:check; then
            echo "::error::Code formatting issues found. Run 'npm run format' to fix formatting."
            exit 1
          fi

      - name: Annotate PR with lint/format suggestions
        if: failure() && github.event_name == 'pull_request'
        run: |
          echo "::notice::If the workflow failed due to linting or formatting issues, you can fix them by running:"
          echo "::notice::  npm run lint:fix  # Fix linting issues"
          echo "::notice::  npm run format   # Fix formatting issues"